# Generated by Django 4.0.3 on 2022-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
