# Generated by Django 4.0.3 on 2022-04-11 10:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_subcategory_post_category_post_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
