# Generated by Django 4.0.3 on 2022-04-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('home', 'Home'), ('popular', 'Popular'), ('recent', 'Recent'), ('comment', 'Comment')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
